apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  source:
    repoURL: https://github.com/cmwylie19/pepr-with-argo
    targetRevision: HEAD
    path: k8s/webapps
  destination:
    server: https://kubernetes.default.svc
    namespace: webapps
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true 
  ignoreDifferences:
    - group: "application.pepr.dev"
      kind: "webapps"
      jsonPointers:
        - /metadata/annotations
